// ── Step: Format Backlog ─────────────────────────────────────────────────
// Stage 6 of req-decompose: Synthesize the full decomposition hierarchy into
// a clean, printable BACKLOG.md — from requirement → EARS → stories → BDD
// scenarios → TDD task list. The living decomposition artifact.

import { none, retry } from "../gates/index.js";
import type { Step } from "../types.js";

export const formatBacklog: Step = {
	kind: "step",
	label: "Format Backlog",
	agent: "resolver",
	description:
		"Synthesize full hierarchy into a BACKLOG.md living decomposition artifact",
	prompt:
		"You are the Backlog Formatter. Produce a clean BACKLOG.md from the full decomposition.\n\n" +
		"Validated TDD task list:\n$INPUT\n\n" +
		"Original requirement:\n$ORIGINAL\n\n" +
		"Produce a structured BACKLOG.md with this hierarchy:\n\n" +
		"```markdown\n" +
		"# Backlog: [requirement title]\n\n" +
		"> Generated by req-decompose pipeline\n\n" +
		"## Decomposition Hierarchy\n\n" +
		"Requirement → EARS requirements → User Stories → BDD Scenarios → TDD Tasks\n\n" +
		"---\n\n" +
		"## Story: STORY-N — [name]\n\n" +
		"**Source REQ:** REQ-X  \n" +
		"**Splitting pattern:** [pattern used]  \n" +
		"**Estimated size:** [hours]  \n\n" +
		"### Scenario N.X: [scenario name]\n\n" +
		"- **Given:** ...\n" +
		"- **When:** ...\n" +
		"- **Then:** ...\n\n" +
		"#### TDD Task List\n\n" +
		"| # | Task | Function | Est |\n" +
		"|---|------|----------|-----|\n" +
		"| TASK-N.X.1 | [test description] | `functionName()` | 10 min |\n\n" +
		"---\n\n" +
		"## Summary\n\n" +
		"| Metric | Count |\n" +
		"|--------|-------|\n" +
		"| EARS Requirements | N |\n" +
		"| User Stories | N |\n" +
		"| BDD Scenarios | N |\n" +
		"| TDD Tasks (atomic) | N |\n" +
		"| Total estimated time | Xh |\n" +
		"```\n\n" +
		"Write the final BACKLOG.md to disk using the write tool.\n" +
		"Also print the full content in a ```markdown code block.",
	gate: none,
	onFail: retry(2),
	transform: { kind: "full" },
};
