// ── CaptainState ──────────────────────────────────────────────────────────
// Pipeline registry, job management, and preset discovery.

import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";
import type { PipelineState, Runnable } from "../core/types.js";
import { describeRunnable } from "../core/types.js";
import { loadTsPipelineFile } from "./loader.js";

// ── FsPort (injectable for tests) ─────────────────────────────────────────

export interface FsPort {
	exists(path: string): boolean;
	readText(path: string): string;
	writeText(path: string, content: string): void;
	mkdirp(path: string): void;
	listFiles(dir: string): readonly string[];
	remove(path: string): void;
}

const realFs: FsPort = {
	exists: (p) => existsSync(p),
	readText: (p) => readFileSync(p, "utf8"),
	writeText: (p, c) => writeFileSync(p, c),
	mkdirp: (p) => mkdirSync(p, { recursive: true }),
	listFiles: (dir) => {
		try {
			return readdirSync(dir);
		} catch {
			return [];
		}
	},
	remove: () => {
		/* no-op for real fs, used in cleanup */
	},
};

// ── Job ───────────────────────────────────────────────────────────────────

export interface CaptainJob {
	readonly id: number;
	readonly state: PipelineState;
	readonly controller: AbortController;
}

// ── State ─────────────────────────────────────────────────────────────────

export class CaptainState {
	pipelines: Record<string, { spec: Runnable }> = {};
	jobs: Map<number, CaptainJob> = new Map();
	private _nextJobId = 1;
	readonly captainDir: string;
	private readonly fs: FsPort;

	constructor(captainDir: string, fs: FsPort = realFs) {
		this.captainDir = captainDir.replace(/\/+$/, "");
		this.fs = fs;
	}

	// ── Job registry ──────────────────────────────────────────────────────

	get runningState(): PipelineState | null {
		const all = [...this.jobs.values()];
		for (let i = all.length - 1; i >= 0; i--) {
			if (all[i].state.status === "running") return all[i].state;
		}
		return all.at(-1)?.state ?? null;
	}

	allocateJob(pipelineState: PipelineState): CaptainJob {
		const id = this._nextJobId++;
		const controller = new AbortController();
		pipelineState.jobId = id;
		const job: CaptainJob = { id, state: pipelineState, controller };
		this.jobs.set(id, job);
		return job;
	}

	killJob(id: number): "killed" | "not-found" | "not-running" {
		const job = this.jobs.get(id);
		if (!job) return "not-found";
		if (job.state.status !== "running") return "not-running";
		job.controller.abort();
		job.state.status = "cancelled";
		job.state.endTime = Date.now();
		return "killed";
	}

	// ── Contract file (IDE autocomplete for pipeline authors) ──────────────

	/** @deprecated Use ensureContractFile */
	ensureCaptainContractFile(cwd: string): void {
		this.ensureContractFile(cwd);
	}

	ensureContractFile(cwd: string): void {
		const piDir = join(cwd, ".pi", "pipelines");
		if (!this.fs.exists(piDir)) this.fs.mkdirp(piDir);

		const contractPath = join(piDir, "captain.ts");
		const apiPath = join(this.captainDir, "api.ts");
		const content = [
			"// Auto-generated by captain — do not edit manually.",
			'// Import from this file to get IDE autocomplete: import { retry, bunTest } from "./captain.ts";',
			`export * from "${apiPath}";`,
		].join("\n");

		if (this.fs.exists(contractPath)) {
			try {
				if (this.fs.readText(contractPath) === content) return;
			} catch {
				/* fall through to write */
			}
		}
		try {
			this.fs.writeText(contractPath, content);
		} catch {
			/* best-effort */
		}
	}

	// ── Preset discovery & loading ─────────────────────────────────────────

	discoverPresets(cwd?: string): { name: string; source: string }[] {
		const piDir = join(cwd ?? process.cwd(), ".pi", "pipelines");
		if (!this.fs.exists(piDir)) return [];
		return this.fs
			.listFiles(piDir)
			.filter((f) => f !== "captain.ts" && f.endsWith(".ts"))
			.map((f) => ({
				name: basename(f, ".ts"),
				source: join(piDir, f),
			}));
	}

	loadPipelineFile(
		filePath: string,
	): Promise<{ name: string; spec: Runnable; source: string }> {
		return loadTsPipelineFile({
			filePath,
			captainDir: this.captainDir,
			pipelines: this.pipelines,
		});
	}

	/** @deprecated Use loadPipelineFile */
	loadTsPipelineFile(
		filePath: string,
	): Promise<{ name: string; spec: Runnable; source: string }> {
		return this.loadPipelineFile(filePath);
	}

	async resolvePreset(
		name: string,
		cwd: string,
	): Promise<{ name: string; spec: Runnable; source?: string } | undefined> {
		const candidate = resolve(cwd, name);
		let filePath = this.fs.exists(candidate)
			? candidate
			: this.fs.exists(name)
				? resolve(name)
				: undefined;

		if (!filePath) {
			const p = join(cwd, ".pi", "pipelines", `${name}.ts`);
			if (this.fs.exists(p)) filePath = p;
		}

		if (!filePath) return undefined;
		return this.loadPipelineFile(filePath);
	}

	// ── Pipeline list ──────────────────────────────────────────────────────

	buildPipelineListLines(cwd?: string): string[] {
		const loaded = Object.entries(this.pipelines).map(
			([name, p]) => `• ${name} (loaded)\n${describeRunnable(p.spec, 2)}`,
		);

		const userSection: string[] = [];
		if (cwd) {
			const presets = this.discoverPresets(cwd);
			const unloaded = presets.filter((p) => !this.pipelines[p.name]);
			if (unloaded.length > 0) {
				userSection.push(
					"",
					"User pipelines in .pi/pipelines/ (captain_load to activate):",
					...unloaded.map((p) => `  • ${p.name}`),
				);
			}
		}
		return [...loaded, ...userSection];
	}
}
